name: flutter_portal
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  analyzer: 6.4.0
  build_runner: ^2.4.11
  http: ^1.2.2
  reflectable: ^4.0.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
